International tests
aimclub/BAMT pull request #105
Opened 2024-02-15 12:31 UTC by PabloKarpacho

Added 2 benchmarks and integrational tests with 4 scripts, covering all networks hyperparameters.

2024-02-15 12:31 UTC, pep8speaks commented
Hello @PabloKarpacho! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`tests/test_Integrational.py`](https://github.com/aimclub/BAMT/blob/250e2940ccffcfbb75dc565839711b40ec312041/tests/test_Integrational.py):

> [Line 113:121](https://github.com/aimclub/BAMT/blob/250e2940ccffcfbb75dc565839711b40ec312041/tests/test_Integrational.py#L113): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (157 > 120 characters)
> [Line 144:121](https://github.com/aimclub/BAMT/blob/250e2940ccffcfbb75dc565839711b40ec312041/tests/test_Integrational.py#L144): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (157 > 120 characters)
> [Line 182:121](https://github.com/aimclub/BAMT/blob/250e2940ccffcfbb75dc565839711b40ec312041/tests/test_Integrational.py#L182): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (157 > 120 characters)
> [Line 190:24](https://github.com/aimclub/BAMT/blob/250e2940ccffcfbb75dc565839711b40ec312041/tests/test_Integrational.py#L190): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 219:121](https://github.com/aimclub/BAMT/blob/250e2940ccffcfbb75dc565839711b40ec312041/tests/test_Integrational.py#L219): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (161 > 120 characters)

2024-02-16 11:34 UTC, jrzkaminski commented
Since we have a `black` code style in the repo, please do 

```bash
pip install black
black tests/test_Integrational.py
```

2024-02-16 11:48 UTC, jrzkaminski commented on tests/test_Integrational.py
> +params = disc_network_params + cont_network_params + hybrid_network_params
Looks better and shorter this way:

```suggestion
# Generate parameter lists using list comprehension and itertools.product
def generate_params(data_path, data_type, additional_params=None):
    params = []
    for opt, score in itertools.product(optimizer, scoring):
        if opt == 'HC':
            base_params = [data_path, False, False, opt, score, data_type]
            if additional_params:
                params.extend([base_params + list(param) for param in itertools.product(*additional_params)])
            else:
                params.append(base_params)
    # Add the 'Evo' optimizer case
    params.append([data_path] + [False, False, 'Evo', ("K2", K2Score), data_type] + (list(additional_params[0]) if additional_params else []))
    return params

disc_network_params = generate_params(discrete_data_path, "Discrete", [('Tectonic regime',)])
cont_network_params = generate_params(continuous_data_path, "Continuous", [(use_mixture, 'target')])
hybrid_network_params = generate_params(hybrid_data_path, "Hybrid", [(use_mixture, has_logit, 'target')])

composite_network_params = [
    (hybrid_data_path, False, False, 'Evo', ("K2", K2Score), "Composite", 'target')]

params = disc_network_params + cont_network_params + hybrid_network_params
```

2024-02-16 11:50 UTC, jrzkaminski requested changes
Please address issues mentioned above before merging

2024-02-17 17:22 UTC, jrzkaminski requested changes

2024-02-17 17:22 UTC, jrzkaminski commented on tests/test_Integrational.py
> +import pytest
please also add this for the `generate_params` function to work

```python
import itertools 
```

2024-03-04 09:12 UTC, Roman223 requested changes

2024-04-10 11:10 UTC, Roman223 approved these changes

2024-04-10 11:11 UTC, Roman223 approved these changes

2024-04-10 15:30 UTC, jrzkaminski approved these changes

2024-06-15 10:42 UTC, merged